name: maunyuci_driver
description: "Aplikasi MauNyuci khusus untuk Driver"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  maunyuci_core:
    path: ../maunyuci_core

    # State Management & Navigation
  get: ^4.6.6

  # UI & Styling
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Maps & Location (Leaflet)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: 10.1.0

  # Hardware & Files
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  permission_handler: ^12.0.1
  dio: ^5.0.0
  flutter_svg: ^2.0.0

  # Utilities
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.4
  lottie: ^3.3.1
  package_info_plus: ^9.0.1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true